name: yarn-nm-install
description: Installs deps via yarn and re-uses the cache
runs:
  using: composite
  steps:
    - name: Restore node_modules
      id: yarn-node-modules-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .yarn/cache
        key:
          ${{ runner.os }}-yarn-mono-nm-node-modules-${{ hashFiles('yarn.lock',
          '.yarnrc.yml', 'package.json', '*/package.json', '*/*/package.json')
          }}

    # Thanks to https://github.com/rafaelbiten for this step https://github.com/microsoft/playwright/issues/7249#issuecomment-1385567519
    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('yarn.lock') }}

    - run: yarn install --immutable --inline-builds
      if: steps.yarn-node-modules-cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        YARN_NM_MODE: 'hardlinks-local'

    - name: Download playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      shell: bash
      run: yarn workspace playground run playwright install --with-deps
