name: Compatibility tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Compatibility-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/yarn-nm-install
      # re-enable the following line if we start to get EINTEGRITY errors again
      # - run: npm cache clean || npm cache verify
      # This will test whether `npm install`/`yarn install` can actually run on each compatibility test fixture. See `compatibility-tests/README.md` for more info.
      - run:
          yarn workspace @theatre/compatibility-tests run install-fixtures
          --verbose
      # after that, we run the jest tests for each fixture
      - run: yarn test:compat
