name: 'Publish Prerelease'
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/yarn-nm-install
      - name: Build the Theatre.js packages
        run: yarn build
      - name: Update .yarnrc.yml with the auth config for the npmPublishRegistry
        run: cat .github/.yarnrc.publish.yml >> .yarnrc.yml
      - name: Publish the Theatre.js packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # LATEST_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        run: yarn zx scripts/prerelease.mjs
