name: Visual regression tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/yarn-nm-install

      - name: Download playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn workspace playground run playwright install --with-deps

      - name: Run e2e tests with percy
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: 'yarn test:e2e:ci'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
